# Generated by Django 4.0.4 on 2022-05-03 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hkumember',
            name='diagnoseDate',
            field=models.DateField(default=datetime.date(2022, 5, 3)),
        ),
    ]
