# Generated by Django 4.0.4 on 2022-04-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='memver',
            new_name='member',
        ),
    ]
