# Generated by Django 4.0.4 on 2022-04-14 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_memver_record_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='datetime',
            new_name='enter_datetime',
        ),
        migrations.AddField(
            model_name='record',
            name='leave_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 21, 51, 48, 465929)),
            preserve_default=False,
        ),
    ]
