# Generated by Django 4.0.4 on 2022-05-03 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hkumember_diagnosedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hkumember',
            name='diagnoseDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
