# Generated by Django 4.0.4 on 2022-05-06 07:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hkumember_diagnosedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hkumember',
            name='diagnoseDate',
        ),
        migrations.CreateModel(
            name='Diagonse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnoseDate', models.DateField(default=django.utils.timezone.now)),
                ('hku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hkumember')),
            ],
        ),
    ]
