# Generated by Django 4.0.4 on 2022-04-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_datetime_record_enter_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hkumember',
            name='id',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='id',
        ),
        migrations.AlterField(
            model_name='hkumember',
            name='hku_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
