# Generated by Django 4.0.4 on 2022-05-06 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_hkumember_diagnosedate_diagonse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagonse',
            name='hku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venue'),
        ),
    ]
