# Generated by Django 4.0.4 on 2022-05-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_diagonse_hku_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagonse',
            old_name='hku_id',
            new_name='members',
        ),
    ]
