from django.shortcuts import render

# Create your views here.
# this function gets the venues visited by the member
def get_venues_visited():
    pass

#this function should get the close contacts as defined by hku
def get_close_contacts():
    pass


#this function inserts a visit record generated by devices into the Record database.
def add_record(request):
    pass